#!/usr/bin/env python3
"""Fail if a fork-owned text file contains a unicode em-dash."""
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
EM_DASH = "—"

# Files that legitimately hold the character. Each needs a reason: an allowlist
# without one grows until it covers the rule.
ALLOWED = {
    # Upstream's own README, vendored as a record of what upstream says.
    # Rewriting its punctuation would make it stop being that record.
    "docs/crosspoint-readme.md",
    # A transliteration table. The key IS the em-dash: this is the code that
    # removes them from comic titles, so deleting it breaks the thing the rule
    # is asking for.
    "tools_local/xkcd/build_pack.py",
    # Trivia question text from the corpus, not prose anyone here wrote.
    "tools_local/trivia/local_panel/pairs_blind.tsv",
    # Generated by the Supabase CLI.
    "server/board/supabase/config.toml",
    # Test fixtures that FEED an em-dash in on purpose. autorelease/ asserts
    # that upstream's em-dash becomes a comma on the release page, so the
    # character is the input to the assertion; trivia/ checks a clue carrying
    # non-ASCII. Rewriting either deletes the thing being tested.
    "host-tests/autorelease/run.sh",
    "host-tests/trivia/run.sh",
    # A FOLDS table, same shape as build_pack.py's: the em-dash is a key, and
    # this is the code that folds it to ASCII before an article reaches the
    # device. Two of these existed and only one was obvious.
    "server/read-bridge/bridge/article.py",
    # This file. It has to name the character to look for it.
    "host-tests/nodash/check_nodash.py",
    # article.py's test. A fold table and the test that feeds it the character
    # are always a pair, and rewriting the input silently turns the assertion
    # into one that proves nothing. This was missed twice: once when the table
    # was restored without its test, and once by a mechanical rewrite that
    # touched both.
    "server/read-bridge/tests/test_api.py",
}

# Directory trees that arrive from a generator rather than being written here.
# Same rule as ALLOWED: each needs a reason, and each names the narrowest prefix
# that covers the generated files and nothing else.
ALLOWED_TREES = (
    # BMad Method, written into the repository by its own installer and
    # overwritten wholesale on every update -- `_bmad/config.toml` opens by
    # saying so. This rule is about what the fork writes, and a rewrite here is
    # undone by the next install, so it would go red again on a schedule nobody
    # controls. The prefixes name `skills/bmad-` rather than `.claude/` so that
    # everything this fork does write under those directories -- the session
    # hook, settings.json, any skill written here -- stays covered.
    ".agents/skills/bmad-",
    ".claude/skills/bmad-",
    "_bmad/",
)


def generated(path):
    return path.startswith(ALLOWED_TREES)


# The trees upstream owns, from the worker contract: the reader, the keyboard and
# settings live in src/activities, the shared widgets in src/components, and lib/
# is upstream's except for the directories this fork added. Ours is
# src/apps_local plus fork additions upstream lacks.
UPSTREAM_TREES = ("src/activities/", "src/components/", "src/network/", "src/util/")


def upstream_owns(path):
    """Did upstream write this file?

    Asking whether the path exists at upstream's TIP is not that question, and
    the difference is a live trap rather than a nicety. On 2026-09-15 upstream
    renamed src/activities/home/RecentBooksActivity.cpp. The file did not change
    here at all, and the tip lookup started answering "no" -- so a file upstream
    has owned all along became fork-owned overnight, its em-dash became ours, and
    every pull request went red on a comment nobody on this side had touched.
    CI was green on trunk right up to the rename and would have gone red on the
    next run of the same commit.

    That is one rename away from happening again: this suite's own note says 149
    upstream files carry em-dashes. So the tip is the fast path and the trees are
    the answer when it misses. A rename inside upstream's own trees does not move
    a file across the fence.
    """
    at_tip = subprocess.run(
        ["git", "cat-file", "-e", f"crosspoint/develop:{path}"],
        cwd=ROOT, capture_output=True).returncode == 0
    if at_tip:
        return True
    return path.startswith(UPSTREAM_TREES)


def main():
    tracked = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                             text=True, check=True).stdout.split("\n")
    checks = 0
    failed = 0
    for rel in tracked:
        if not rel or rel in ALLOWED or generated(rel):
            continue
        f = ROOT / rel
        if not f.is_file():
            continue
        try:
            body = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue  # binary, or a font that merely looks like text
        if EM_DASH not in body:
            continue
        if upstream_owns(rel):
            continue
        checks += 1
        failed += 1
        for n, line in enumerate(body.splitlines(), 1):
            if EM_DASH in line:
                print(f"  FAIL {rel}:{n}: em-dash. Use a period, comma, colon, "
                      f"semicolon or parentheses.")
                print(f"       {line.strip()[:100]}")

    # A pass has to assert something, or a run that scanned nothing at all --
    # a broken ls-files, a bad cwd -- reports exactly what a clean tree does.
    if failed == 0:
        checks = 1
    print(f"{checks} checks, {failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
