#!/bin/sh
# Live's arithmetic on a laptop: the interval clamp, the capped backoff, the
# clock plausibility floor and the one wake rule.
#
#   host-tests/live/run.sh
#
# Nothing here touches a card, a radio or a panel, which is the point: the
# failure the backoff exists to prevent is a battery three weeks out, and the
# due-now rule only misbehaves on the sleep AFTER the one you were watching.
# Neither is observable by looking at a device.
set -e
cd "$(dirname "$0")"
BUILD_DIR="${TMPDIR:-/tmp}/$(basename "${CXX:-c++}")-live-tests-$(cd ../.. && pwd | cksum | cut -d" " -f1)"
mkdir -p "$BUILD_DIR"

# THE SERVICE'S THREE NUMBERS, read out of the service rather than typed here.
#
# The reader holds a copy of all three: the clamp it applies to X-Next-Wake and
# the interval it seeds itself with before the service has ever spoken. They are
# two copies of one fact and one of them drifted -- six hours against a day --
# and nothing anywhere could have noticed, because neither side had the other's
# number. Generated, so a change on either side fails this run.
python3 - ../../server/fridge-bridge/bridge/store.py > "$BUILD_DIR/service_limits.generated.h" <<'PY'
import ast
import sys

tree = ast.parse(open(sys.argv[1]).read())
want = {"DEFAULT_INTERVAL_S", "MIN_INTERVAL_S", "MAX_INTERVAL_S"}
found = {}
for node in tree.body:
    if not isinstance(node, ast.Assign):
        continue
    for target in node.targets:
        if isinstance(target, ast.Name) and target.id in want:
            found[target.id] = int(eval(compile(ast.Expression(node.value), "<s>", "eval"), {}, {}))
missing = want - set(found)
if missing:
    sys.exit("live: store.py no longer defines %s, so the reader's copy is unchecked" % ", ".join(sorted(missing)))

print("// Generated by host-tests/live/run.sh from server/fridge-bridge/bridge/store.py.")
for name, value in sorted(found.items()):
    print("constexpr long kService%s = %d;" % (name.title().replace("_", ""), value))
PY

"${CXX:-c++}" -std=c++17 -O1 -Wall -Wextra -Werror -I"$BUILD_DIR" \
  ../../src/apps_local/live/LiveCore.cpp \
  test_live.cpp -o "$BUILD_DIR/test_live"
"$BUILD_DIR/test_live"
