#!/bin/sh
# Walks every built-in wallpaper name and the "+ Add" tile through the picker's
# real geometry and the real toybox cuts, and fails if the selection marker can
# touch the artwork or a caption in any grid position.
#
#   host-tests/wallcaption/run.sh
#
# Links lib/EpdFont and the generated font headers on purpose: host-tests/ui
# measures ten pixels a character, which cannot see a caption overflow a 165px
# cell in a real face.
#
# It links LiveCore too, so the Live screen is driven by the phrases the DEVICE
# composes rather than by plausible-looking strings typed here. The headline is
# the one element on that screen whose failure is silent -- fittedTitle steps it
# down a cut rather than refusing -- and "In about 45 minutes" is 464px against
# a 448px body, so the question "does every phrase this can produce keep the
# display cut" can only be answered by measuring the real phrases in the real
# face. A list of examples in the test would answer it for the examples.
set -e
cd "$(dirname "$0")"
BUILD_DIR="${TMPDIR:-/tmp}/$(basename "${CXX:-c++}")-wallcaption-tests-$(cd ../.. && pwd | cksum | cut -d" " -f1)"
mkdir -p "$BUILD_DIR"
# THE SERVICE'S OWN SENTENCES, extracted from the service rather than copied.
#
# The Live screen draws a bridge refusal verbatim -- the device does not get to
# reword a decision somebody else made -- so the strings that have to fit its
# report region are refused() calls in server/fridge-bridge/bridge/app.py, not
# strings anyone types here. A list typed into the test would keep measuring the
# old sentences after the service edited one, and stay green while the panel cut
# the new one (derived-facts-written-as-literals). So it is generated, every run.
APP=../../server/fridge-bridge/bridge/app.py
GEN="$BUILD_DIR/service_refusals.generated.h"
# READ OUT OF THE PARSED SOURCE, not off its lines. The first version of this
# grepped `refused("..."` with sed and it was answered by LAYOUT: a formatter
# wrapped two calls so the sentence sat on its own line, the pattern matched
# neither, and the corpus silently lost the two longest sentences on the screen
# -- with this suite still reporting 14944 checks and 0 failed. A generated list
# that quietly gets shorter is worse than a typed one, because it still looks
# derived. The AST cannot be fooled by wrapping, and the count below means an
# extractor that stops working fails the run instead of thinning the corpus.
python3 - "$APP" > "$GEN" <<'PY'
import ast
import sys

src = open(sys.argv[1]).read()
tree = ast.parse(src)
calls = [n for n in ast.walk(tree)
         if isinstance(n, ast.Call) and isinstance(n.func, ast.Name) and n.func.id == "refused"]
if not calls:
    sys.exit("wallcaption: app.py has no refused() calls at all; the corpus would be empty")

out = set()
unread = []
for call in calls:
    if not call.args:
        unread.append(call.lineno)
        continue
    arg = call.args[0]
    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
        out.add(arg.value)
    elif isinstance(arg, ast.JoinedStr):
        # f-strings interpolate the cap; MAX_SENDERS is 4, substituted so the
        # string measured is the string sent. Any OTHER placeholder is a
        # sentence this cannot know the words of, and is dropped by name rather
        # than by a grep for a brace.
        text = ""
        for piece in arg.values:
            if isinstance(piece, ast.Constant):
                text += str(piece.value)
            elif ast.unparse(piece.value) == "store.MAX_SENDERS":
                text += "4"
            else:
                text = None
                break
        if text is not None:
            out.add(text)
    else:
        unread.append(call.lineno)
if unread:
    sys.exit("wallcaption: refused() at line(s) %s carries no literal this can read, "
             "so its sentence would go unmeasured" % ", ".join(str(n) for n in unread))

print("// Generated by host-tests/wallcaption/run.sh from server/fridge-bridge/bridge/app.py.")
print("static const char* kServiceRefusals[] = {")
for text in sorted(out):
    print('  "%s",' % text.replace("\\", "\\\\").replace('"', '\\"'))
print("};")
PY

# AND THE SENTENCE THE SERVICE SENDS WHEN THE SCHEDULE HAS MOVED.
#
# `pending` on GET /api/senders is drawn on the reader verbatim, and it is not a
# refused() call, so the extractor above cannot see it: a sentence the reader
# displays and nobody measures is exactly the hole clean-list-hides-absence is
# about. It is a TEMPLATE over a finite set of cadence phrases, so the corpus
# measured here is the whole cross product rather than a representative of it.
#
# store.ALLOWED_INTERVALS is finite for this reason. Widen it to a range and
# this generator stops the run rather than quietly measuring the six it knew.
python3 - ../../server/fridge-bridge/bridge >> "$GEN" <<'PENDING'
import ast
import pathlib
import sys

root = pathlib.Path(sys.argv[1])


def literal(source, name):
    for node in ast.parse(source).body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return ast.literal_eval(node.value)
    sys.exit("wallcaption: %s is gone from the service, so its sentences would go unmeasured" % name)


intervals = literal((root / "store.py").read_text(), "ALLOWED_INTERVALS")
words = literal((root / "store.py").read_text(), "INTERVAL_WORDS")
template = literal((root / "app.py").read_text(), "PENDING_TEMPLATE")
if not isinstance(intervals, tuple) or not intervals:
    sys.exit("wallcaption: ALLOWED_INTERVALS is no longer a finite tuple, so the pending corpus cannot be enumerated")
missing = [i for i in intervals if i not in words]
if missing:
    sys.exit("wallcaption: no words for interval(s) %s; the reader would be sent a phrase nobody measured" % missing)

phrases = [words[i] for i in intervals]
# Every clock time is the same length in 24-hour form, but not the same WIDTH:
# which digits are widest is a property of the face, so three are measured
# rather than one being reasoned about.
phrases += ["%02d:%02d daily" % (h, m) for h, m in ((0, 0), (8, 45), (23, 59))]

print("// Generated by host-tests/wallcaption/run.sh from the service's schedule words.")
print("static const char* kPendingSentences[] = {")
for phrase in sorted(set(phrases)):
    text = template.format(phrase)
    print('  "%s",' % text.replace("\\", "\\\\").replace('"', '\\"'))
print("};")
PENDING

# AND THE DEVICE'S OWN SENTENCES, from the two layers under the screen.
#
# The service's refusals were generated and the TRANSPORT's were not, so half
# the foreign sentences this screen draws went unmeasured -- and the longest of
# them, "Could not reach the sync service. Check Wi-Fi and try again.", is the
# one a reader with no Wi-Fi sits on. It reached the panel as three words a
# screen high, through the footer and off the bottom, and this suite stayed
# green because every string it measured was short (clean-list-hides-absence).
#
# Deliberately OVER-inclusive: any sentence-shaped literal in these files,
# rather than only the ones assigned to `message`. A `? "a" : "b"` and a helper
# that returns one are both real paths to the screen, and a scanner that
# recognised only the obvious assignment would have missed them silently. What
# it must never do is come back empty or nearly so, which the floor below
# catches.
BRIDGE_SRC="../../src/apps_local/bridge/BridgeHttp.cpp ../../src/apps_local/live/LiveBridge.cpp ../../src/apps_local/live/LiveEngine.cpp"
python3 - $BRIDGE_SRC >> "$GEN" <<'PY'
import re
import sys

LITERAL = re.compile(r'"(?:[^"\\\n]|\\.)*"')
out = set()
for path in sys.argv[1:]:
    text = open(path).read()
    # Comments first: this file's prose is full of quoted sentences and none of
    # them is drawn anywhere.
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    for match in LITERAL.findall(text):
        body = match[1:-1]
        if "%" in body or "\\" in body:
            continue
        if " " not in body or not body.endswith((".", "!")):
            continue
        out.add(body)

# A floor, not an exact count: the point is that a scanner which stops working
# fails the run rather than quietly measuring nothing.
if len(out) < 8:
    sys.exit("wallcaption: only %d device sentences found in %s; the extractor has stopped working"
             % (len(out), " ".join(sys.argv[1:])))

print("// Generated by host-tests/wallcaption/run.sh from the bridge and Live sources.")
print("static const char* kDeviceSentences[] = {")
for text in sorted(out):
    print('  "%s",' % text.replace('"', '\\"'))
print("};")
PY

SDK=../../freeink-sdk/libs/ui/FreeInkUI
ICONS=../../freeink-sdk/libs/assets/Icons
SRC=../../src/apps_local/wallpapers
"${CXX:-c++}" -std=c++17 -O1 -Wall -Wextra -Werror -Wno-comment -Wno-missing-field-initializers \
  -I"$BUILD_DIR" -I"$SDK/include" -I"$ICONS/include" -I../../lib/EpdFont -I../../lib/Utf8 \
  "$SDK/src/FreeInkUI.cpp" \
  $SRC/WallpapersCore.cpp $SRC/WallpapersScreens.cpp \
  ../../src/apps_local/live/LiveCore.cpp \
  ../../lib/EpdFont/EpdFont.cpp ../../lib/EpdFont/EpdFontFamily.cpp ../../lib/Utf8/Utf8.cpp \
  test_wallcaption.cpp -o "$BUILD_DIR/test_wallcaption"
"$BUILD_DIR/test_wallcaption"
