#!/bin/bash
# Regenerate src/apps_local/cards/CardSuits.h, the deck's suit pips. Shared by
# every card game; the SVGs it reads still live under solitaire/.
#
#   brew install librsvg          # rsvg-convert, the only external dependency
#   ./tools_local/solitaire/gen_suit_icons.sh
#
# The output is committed, because regenerating needs librsvg and a checkout
# should build without it. Edit the manifests or SVGs, run this, commit both.
#
# The suits are the Unicode card-suit glyphs (U+2660, U+2665, U+2666, U+2663)
# from Noto Sans Symbols 2 (OFL), extracted to SVG with fontTools; no font
# binary ships on the device. See src/apps_local/solitaire/art/README.md for
# why this set and not Lucide or the traditional Wikimedia one, both of which
# lose the club/spade distinction at index size.
#
# Two passes into one header: *-solid.svg is the glyph as drawn, for the black
# suits; *-outline.svg is the same path unfilled and stroked, which is the
# hollow form the red suits use. Deriving both from one path means they cannot
# drift apart.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"

ART=src/apps_local/solitaire/art
OUT=src/apps_local/cards/CardSuits.h
SOLID="$(mktemp -t suits_solid).h"
OUTLINE="$(mktemp -t suits_outline).h"
trap 'rm -f "$SOLID" "$OUTLINE"' EXIT

# Two sizes, generated rather than scaled: 18 for a corner index, 46 for a card
# centre and the back's mark. Downscaling a 1-bit bitmap destroys it.
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest "$ART/suits.txt" --svgdir "$ART" --sizes 18,46 --out "$SOLID"
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest "$ART/suits-outline.txt" --svgdir "$ART" --sizes 18,46 --out "$OUTLINE"

{
  printf '#pragma once\n\n'
  printf "// Solitaire's suit artwork. Generated by tools_local/solitaire/gen_suit_icons.sh; do not edit.\n"
  printf '//\n'
  printf '// The Unicode card-suit glyphs from Noto Sans Symbols 2, Copyright 2022 The\n'
  printf '// Noto Project Authors, SIL Open Font License 1.1 (art/OFL.txt). Emitted by the\n'
  printf "// SDK's own generator as freeink::Icon, which carries opticalCenterY -- the row\n"
  printf "// of the artwork's centre of mass, measured from the real pixels. That is what\n"
  printf '// makes a heart and a spade sit on the same optical line without per-suit\n'
  printf '// nudging.\n'
  printf '//\n'
  printf '// Two sizes, generated rather than scaled: 18px for a corner index, 46px for a\n'
  printf "// card centre and the back's mark. Nothing resamples.\n\n"
  sed '/^#pragma once$/d' "$SOLID"
  sed '/^#pragma once$/d;/#include "Icon.h"/d' "$OUTLINE"
} > "$OUT"

# gen_icons.py was written for Lucide and says so unconditionally. These glyphs
# are not Lucide's, so relabel rather than ship the attribution of the set we
# rejected. Twice, not once: this header is two generator passes concatenated.
WRONG="// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit."
RIGHT="// Generated by tools_local/solitaire/gen_suit_icons.sh from $ART/*.svg. Do not edit."
grep -qF "$WRONG" "$OUT" || { echo "gen_icons.py banner changed; update gen_suit_icons.sh" >&2; exit 1; }
uv run --quiet python -c "
import sys
path, wrong, right = sys.argv[1:4]
text = open(path).read()
assert text.count(wrong) == 2, f'expected 2 banners, found {text.count(wrong)}'
open(path, 'w').write(text.replace(wrong, right))
" "$OUT" "$WRONG" "$RIGHT"

./bin/clang-format-fix >/dev/null 2>&1 || clang-format -i "$OUT"
echo "wrote $OUT"
